# Generated by Django 4.0 on 2022-01-03 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_booksmodel_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
