# Generated by Django 4.0 on 2022-01-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_booksmodel_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likesreadsmodel',
            old_name='likes',
            new_name='like',
        ),
    ]
