# Generated by Django 4.0 on 2022-01-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_likes_likesreadsmodel_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='email_id',
            field=models.CharField(max_length=100),
        ),
    ]
