# Generated by Django 4.0 on 2022-01-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_usersmodel_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='email_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
