version: '3.8'
services:
  db:
    hostname: db
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=user_interactions
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33066:3306
    volumes:
      - .dbdata:/var/lib/mysql

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py db init && python manage.py db migrate && python manage.py db upgrade"
    volumes:
      - user_interactions_app:/app
    links:
      - db
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python main.py"
    ports:
      - 8001:5000
    volumes:
      - user_interactions_app:/app
    links:
      - db
    depends_on:
      - migration

  queue:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python consumer.py"
    links:
      - db
    depends_on:
      - backend

volumes:
  user_interactions_app:
