version: '3.8'
services:
  db:
    hostname: db
    image: mysql:5.7.22
    restart: always
    environment:
      - MYSQL_DATABASE=user_interactions
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - .dbdata:/var/lib/mysql

  # migration:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: 'python manage.py db init && python manage.py db migrate && python manage.py db upgrade'
  #   volumes:
  #     - user_interactions_app:/app
  #   depends_on:
  #     - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    ports:
      - 8001:5000
    volumes:
      - user_interactions_app:/app
    depends_on:
      - db

  queue:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
      - backend

volumes:
  user_interactions_app:
