version: '3.8'
services:
  db:
    hostname: db
    image: 'postgres:11.14'
    restart: always
    environment:
      - POSTGRES_DB=contentservice
      - POSTGRES_USER=ssvijayg
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data/

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py makemigrations && python3 manage.py migrate'
    volumes:
      - content_service_app:/app
    depends_on:
      - 'db'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - content_service_app:/app
    depends_on:
      - 'db'
      - 'migration'

  queue:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python consumer.py'
    depends_on:
      - 'backend'

volumes:
  content_service_app:
