version: '3.8'
services:
  db:
    hostname: db
    image: 'postgres:11.14'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=contentservice
      - POSTGRES_USER=ssvijayg
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    ports:
      - 8000:8000
    volumes:
      - content_service_app:/app
    links:
      - db
    depends_on:
      - db

  queue:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate && python consumer.py"
    depends_on:
      - db
      - backend

volumes:
  content_service_app:
